#1
CREATE TABLE CLASS(`id` INT PRIMARY KEY NOT NULL,`name` VARCHAR(30)  NOT NULL);
#2
INSERT INTO CLASS(`id`,  `name`)VALUES (1, 'RICHARD');
SELECT*FROM CLASS;
#3
START TRANSACTION;
UPDATE CLASS SET name='SANTHOSH' WHERE id= 1;
SAVEPOINT A;
ROLLBACK TO A;
SELECT*FROM CLASS;
INSERT INTO CLASS VALUES (2, 'SUNIL');
SAVEPOINT B;
ROLLBACK TO B;
SELECT*FROM CLASS;
INSERT INTO CLASS VALUES (3, 'HARRIS');
SAVEPOINT C;
ROLLBACK TO C;
SELECT*FROM CLASS;
INSERT INTO CLASS VALUES (4, 'SMITH');
SAVEPOINT D;
ROLLBACK TO D;
SELECT*FROM CLASS;
INSERT INTO CLASS VALUES (5, 'AARON');
SAVEPOINT E;
SELECT*FROM CLASS;
ROLLBACK TO E;
COMMIT;